/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = import.meta.env.VITE_PROJECT_ID;
export const tenantId = import.meta.env.VITE_TENANT_ID;
export const publicAnonKey = import.meta.env.VITE_PUBLIC_ANON_KEY;

export const FORGOT_PASSWORD_REDIRECT = `${window.location.origin}/reset-password`;