/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_991766ee (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/qmcbbwpwvezvrihtsyqr/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const client = (authHeader?: string) => {
  if (authHeader) {
    return createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_ANON_KEY")!,
      { global: { headers: { Authorization: authHeader } } }
    );
  }
  return createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
  );
};

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any, authHeader?: string): Promise<void> => {
  const supabase = client(authHeader)
  const { error } = await supabase.from("kv_store_991766ee").upsert({
    key,
    value
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string, authHeader?: string): Promise<any> => {
  const supabase = client(authHeader)
  const { data, error } = await supabase.from("kv_store_991766ee").select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string, authHeader?: string): Promise<void> => {
  const supabase = client(authHeader)
  const { error } = await supabase.from("kv_store_991766ee").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[], authHeader?: string): Promise<void> => {
  const supabase = client(authHeader)
  const { error } = await supabase.from("kv_store_991766ee").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[], authHeader?: string): Promise<any[]> => {
  const supabase = client(authHeader)
  const { data, error } = await supabase.from("kv_store_991766ee").select("value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[], authHeader?: string): Promise<void> => {
  const supabase = client(authHeader)
  const { error } = await supabase.from("kv_store_991766ee").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string, authHeader?: string): Promise<any[]> => {
  const supabase = client(authHeader)
  const { data, error } = await supabase.from("kv_store_991766ee").select("key, value").like("key", prefix + "%");
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};