name: Deploy backend
on:
  push:
    branches:
      - staging
      - production

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    permissions:
      contents: read
      id-token: write
      actions: read
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1
      - name: Install Supabase CLI
        uses: supabase/setup-cli@46f7f98c7f948ad727d22c1e67fab04c223a0520 # v3.0.0
        with:
          version: latest
      - name: Set secrets
        run: |
          supabase secrets set --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} \
            ALLOWED_ORIGINS=${{ vars.SUPABASE_ALLOWED_ORIGINS }} \
            APPSIGNAL_API_KEY=${{ secrets.SUPABASE_APPSIGNAL_API_KEY }}
      - name: Link Supabase project
        working-directory: ./src
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}
      - name: Deploy Supabase functions
        working-directory: ./src
        run: supabase functions deploy
