name: Deploy
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'index.html'
      - 'package.json'
      - 'package-lock.json'
      - 'vite.config.json'
      - 'firebase.json'
      - '.firebaserc'

jobs:
  deploy-frontend:
    name: Deploy frontend
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: '25.8.1'
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@e2eda2e106cfa35cdbcf4ac9ddaf6c4756df2c8c # v0.10.0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}"
          projectId: "${{ vars.FIREBASE_PROJECT_ID }}"
          channelId: live

  deploy-backend:
    name: Deploy backend
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      actions: read
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: '25.8.1'
      - name: Install Supabase CLI
        working-directory: ./src
        run: npm install -g supabase
      - name: Link Supabase project
        working-directory: ./src
        run: supabase link --project-ref ${{ vars.SUPABASE_PROJECT_ID }}
      - name: Deploy Supabase functions
        working-directory: ./src
        run: supabase functions deploy
