name: Deploy frontend
on:
  push:
    branches:
      - staging
      - production
    # paths:
    #   - 'src/**'
    #   - 'index.html'
    #   - 'package.json'
    #   - 'package-lock.json'
    #   - 'vite.config.json'
    #   - 'firebase.json'
    #   - '.firebaserc'

jobs:
  deploy-bukit-merah:
    permissions:
      contents: read
      id-token: write
      actions: read
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/reusable-deploy-frontend.yml
    with:
      environment: ${{ github.ref_name }}
      firebase_target: 'bukit-merah'
      tenant: 'bukit_merah'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      firebase_project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
      firebase_service_account_key: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
      supabase_project_id: ${{ secrets.SUPABASE_PROJECT_ID }}
      supabase_public_anon_key: ${{ secrets.SUPABASE_PUBLIC_ANON_KEY }}
