name: Reusable frontend deploy
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      node_version:
        required: false
        type: string
        default: '25.8.2'
      firebase_target:
        required: true
        type: string
      tenant:
        required: true
        type: string
    secrets:
      gh_token:
        required: true
      firebase_project_id:
        required: true
      firebase_service_account_key:
        required: true
      supabase_project_id:
        required: true
      supabase_public_anon_key:
        required: true
      appsignal_api_key:
        required: true
    outputs:
      build-status:
        description: "The status of the build job"
        value: ${{ jobs.build.outputs.status }}
jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      id-token: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node_version }}
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
        env:
          VITE_PROJECT_ID: ${{ secrets.supabase_project_id }}
          VITE_TENANT_ID: ${{ inputs.tenant }}
          VITE_PUBLIC_ANON_KEY: ${{ secrets.supabase_public_anon_key }}
          VITE_APPSIGNAL_API_KEY: ${{ secrets.appsignal_api_key }}
      - run: echo "Deploying to target ${{ inputs.fir${{ secrets.supabase_public_anon_key }}ebase_target }}"
      - uses: FirebaseExtended/action-hosting-deploy@e2eda2e106cfa35cdbcf4ac9ddaf6c4756df2c8c # v0.10.0
        with:
          repoToken: "${{ secrets.gh_token }}"
          firebaseServiceAccount: "${{ secrets.firebase_service_account_key }}"
          projectId: "${{ secrets.firebase_project_id }}"
          target: ${{ inputs.firebase_target }}
          channelId: live
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
