name: Supabase Schema Diff
on:
  pull_request:

jobs:
  supabase-schema-diff:
    name: Supabase Schema Diff
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      actions: read
      pull-requests: write
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Link Supabase project
        working-directory: ./src
        run: supabase link --project-ref ${{ vars.SUPABASE_PROJECT_ID }}
      - name: Supabase schema diff
        id: diff
        working-directory: ./src
        run: supabase db diff --linked
      - name: Create PR comment
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        with:
          issue-number: ${{ github.event.number }}
          body: |
            Build output:
            ${{ steps.diff.outputs.stdout }}
