name: Supabase Schema Diff
on:
  pull_request:
    paths:
      - 'src/supabase/schemas/**'
      - 'src/supabase/migrations/**'

jobs:
  supabase-schema-diff:
    name: Supabase Schema Diff
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      actions: read
      pull-requests: write
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Link Supabase project
        working-directory: ./src
        run: supabase link --project-ref ${{ vars.SUPABASE_PROJECT_ID }}
      - name: Schema pull
        id: diff
        working-directory: ./src
        run: supabase db pull
      - name: Schema diff
        id: diff
        working-directory: ./src
        run: supabase db diff --linked
