name: Supabase Schema Diff
on:
  pull_request:

jobs:
  supabase-schema-diff:
    name: Supabase Schema Diff
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      actions: read
      pull-request: write
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: '25.8.1'
      - name: Install Supabase CLI
        working-directory: ./src
        run: npm install -g supabase
      - name: Link Supabase project
        working-directory: ./src
        run: supabase link --project-ref ${{ vars.SUPABASE_PROJECT_ID }}
      - name: Supabase schema diff
        working-directory: ./src
        run: supabase db diff --linked
